# 제로베이스 데이터 사이언스 스쿨 3기 SQL 과제 2
- 유가 데이터 분석

### 8문제 총 100점

- 1번 5점
- 2번 5점
- 3번 10점
- 4번 30점
- 5번 10점
- 6번 10점
- 7번 15점
- 8번 15점

### 1 ~ 8번 모두 본 노트북 파일에 답안 작성해서 제출해주세요 :)

In [3]:
import pandas as pd
import mysql.connector

In [4]:
conn = mysql.connector.connect(
    host='database-1.c7pudh9fimyp.ap-southeast-2.rds.amazonaws.com',
    port=3306,
    user='admin',
    password='Kjh9099!',
    database='oneday'
)

In [5]:
cursor = conn.cursor(buffered=True)

In [8]:
sql = "GRANT ALL PRIVILEGES on oneday.* To 'oneday'@'%'"
cursor.execute(sql)

In [6]:
conn.close()

In [7]:
conn = mysql.connector.connect(
    host='database-1.c7pudh9fimyp.ap-southeast-2.rds.amazonaws.com',
    port=3306,
    user='oneday',
    password='1234',
    database='oneday'
)

In [8]:
cursor = conn.cursor(buffered=True)

---

문제 1.

주유소 데이터를 저장할 테이블을 다음의 구조로 생성하세요. (PDF 파일 참고)

In [12]:
sql = 'create table GAS_BRAND (id int AUTO_INCREMENT PRIMARY KEY, name varchar(16))'
cursor = conn.cursor(buffered=True)
cursor.execute(sql)

In [14]:
sql = 'create table GAS_STATION (id int AUTO_INCREMENT PRIMARY KEY, brand int, name varchar(64), city char(2), gu varchar(10), address varchar(128), gasoline int, diesel int, self boolean, car_wach boolean, charging_station boolean, car_maintenance boolean, convenience_store boolean, 24_hours boolean, lat DECIMAL(16, 4), lng DECIMAL(17,14),FOREIGN KEY (brand) REFERENCES GAS_BRAND(id))'
cursor = conn.cursor(buffered=True)
cursor.execute(sql)

문제 2.

Python 코드로 GAS_BRAND 데이터를 다음과 같이 입력하고 확인하세요. (PDF 파일 참고)

In [137]:
cursor.execute('insert into GAS_BRAND values (1, "SK에너지")')
cursor.execute('insert into GAS_BRAND values (2, "HD현대오일뱅크")')
cursor.execute('insert into GAS_BRAND values (3, "GS칼텍스")')
cursor.execute('insert into GAS_BRAND values (4, "S-OIL")')
cursor.execute('insert into GAS_BRAND values (5, "알뜰주유소")')
cursor.execute('insert into GAS_BRAND values (6, "자가상표")')

제출 1.
- Table 생성 결과 : Desc GAS_BRAND; Desc GAS_STATION;

In [138]:
cursor.execute('Desc GAS_BRAND')
cursor.fetchall()

[('id', 'int', 'NO', 'PRI', None, 'auto_increment'),
 ('name', 'varchar(16)', 'YES', '', None, '')]

In [139]:
cursor.execute('Desc GAS_STATION')
cursor.fetchall()

[('id', 'int', 'NO', 'PRI', None, 'auto_increment'),
 ('brand', 'int', 'YES', 'MUL', None, ''),
 ('name', 'varchar(64)', 'YES', '', None, ''),
 ('city', 'char(2)', 'YES', '', None, ''),
 ('gu', 'varchar(10)', 'YES', '', None, ''),
 ('address', 'varchar(128)', 'YES', '', None, ''),
 ('gasoline', 'int', 'YES', '', None, ''),
 ('diesel', 'int', 'YES', '', None, ''),
 ('self', 'tinyint(1)', 'YES', '', None, ''),
 ('car_wach', 'tinyint(1)', 'YES', '', None, ''),
 ('charging_station', 'tinyint(1)', 'YES', '', None, ''),
 ('car_maintenance', 'tinyint(1)', 'YES', '', None, ''),
 ('convenience_store', 'tinyint(1)', 'YES', '', None, ''),
 ('24_hours', 'tinyint(1)', 'YES', '', None, ''),
 ('lat', 'decimal(16,4)', 'YES', '', None, ''),
 ('lng', 'decimal(17,14)', 'YES', '', None, '')]

제출 2.
- GAS_BRAND 조회 결과 : SELECT * FROM GAS_BRAND;

In [140]:
# gas_brand 조회
cursor.execute('SELECT * FROM GAS_BRAND')
cursor.fetchall()

[(1, 'SK에너지'),
 (2, 'HD현대오일뱅크'),
 (3, 'GS칼텍스'),
 (4, 'S-OIL'),
 (5, '알뜰주유소'),
 (6, '자가상표')]

문제 3.

다음의 함수와 그 함수를 테스트하는 코드를 작성하세요. (PDF 파일 참고)

- 화폐단위 문자형을 입력받아 숫자형으로 반환하는 함수 (테스트 입력 : ‘1,000’)
- 주유소 브랜드를 입력하면 GAS_BRAND 데이터를 참고하여 ID 를 반환하는 함수 (테스트 입력 : ‘SK에너지’) 
- 주소를 입력받아 구 이름을 반환하는 함수 (테스트 입력 : ‘서울시 강남구 헌릉로 730’)
- 주소를 입력받아 위도, 경도를 반환하는 함수 (테스트 입력 : ‘서울시 강남구 헌릉로 730’)

제출 3.
- 각 함수 및 테스트 코드와 실행결과

In [23]:
# 1. 화폐단위 문자형을 입력받아 숫자형으로 반환하는 함수 (테스트 입력 : ‘1,000’)
def Toint(num):
    number = num.replace(',', '')
    return int(number)

In [27]:
a = Toint('103,1234,1234')
b = Toint('1,000')
print(a, b)

10312341234 1000

In [141]:
# 2. 주유소 브랜드를 입력하면 GAS_BRAND 데이터를 참고하여 ID 를 반환하는 함수 (테스트 입력 : ‘SK에너지’)
cursor.execute('SELECT * FROM GAS_BRAND')
a = cursor.fetchall()
gas_id = dict(a)

def brand_sch(brand):
    for i in gas_id.items():
        if brand in ['SK에너지', 'HD현대오일뱅크', 'GS칼텍스', 'S-OIL', '알뜰주유소']:
            if brand == i[1]:
                return i[0]
        else:
            return 6

In [142]:
brand_sch('SK에너지'), brand_sch('HD현대오일뱅크'), brand_sch('GS칼텍스'), brand_sch('S-OIL'), brand_sch('알뜰주유소'), brand_sch('아무주유소')

(1, 2, 3, 4, 5, 6)

In [48]:
# 3. 주소를 입력받아 구 이름을 반환하는 함수 (테스트 입력 : ‘서울시 강남구 헌릉로 730’)
def gu_sch(address):
    return address.split(' ')[1]
gu_sch('서울시 강남구 헌릉로 730')

'강남구'

In [199]:
gmaps.geocode('서울시 강남구 헌릉로'+'주유소')[0]['geometry']['location']

{'lat': 37.4659155, 'lng': 127.1122506}

In [201]:
# 4. 주소를 입력받아 위도, 경도를 반환하는 함수 (테스트 입력 : ‘서울시 강남구 헌릉로 730’)
import googlemaps
gkey = 'AIzaSyDCCSzEJpBtSlc_6Uq34i2AbJjBeNixKwA'
gmaps = googlemaps.Client(key=gkey)
def lat_lng_sch(address):
    lat_lng = gmaps.geocode(address)[0]['geometry']['location']
    return lat_lng['lat'], lat_lng['lng']

In [370]:
lat_lng_sch('서울시 강남구 헌릉로 730')

(37.4665675, 127.1190803)

문제 4.

Python 코드에서 주유소 페이지에서 데이터를 가져올때, GAS_STATION 테이블에 바로 입력하도록 수정하세요. (앞서 생 성한 함수활용)
- 주의. city 는 ‘서울’ 로 고정, 부가정보 데이터 타입
- 입력된 데이터의 총 갯수를 쿼리하여 결과를 확인합니다. - 입력된 데이터 상위 10개를 쿼리하여 결과를 확인합니다.


제출 4.
- 주유소 데이터 관련 코드 (ipynb)

In [312]:
cursor.execute('DELETE FROM GAS_STATION')
cursor.execute('select * from GAS_STATION')
cursor.fetchall()

[]

In [107]:
import numpy as np
import pandas as pd
import folium
import requests
import time
from selenium import webdriver
from bs4 import BeautifulSoup
from selenium.webdriver.common.by import By

In [336]:
driver.quit()

In [314]:
driver = webdriver.Chrome()
url = 'https://www.opinet.co.kr/searRgSelect.do'
driver.get(url)
time.sleep(2)

# 선택할 지역(시/도) 리스트 뽑아오기
sido_list_raw = driver.find_element(By.CSS_SELECTOR, '#SIDO_NM0')
sido_list = sido_list_raw.find_elements(By.CSS_SELECTOR, 'option')
sido_list = sido_list[1:]
sido_names = [option.get_attribute('value') for option in sido_list]

# 지역 선택 (서울시)
sido_list_raw.send_keys(sido_names[0])
time.sleep(2)

# 선택할 지역(구) 리스트 뽑아오기
gu_list_raw = driver.find_element(By.CSS_SELECTOR, '#SIGUNGU_NM0')
gu_list = gu_list_raw.find_elements(By.CSS_SELECTOR, 'option')
gu_list = gu_list[1:]
gu_names = [option.get_attribute('value') for option in gu_list]

In [146]:
def oil_name(name):
    if '㈜' in name:
        return '(주)' + name.split('㈜')[1]
    else:
        return name

In [303]:
len(soup.find_all(id='self_icon'))

1

In [300]:
# 셀프주유소: 길이가 0이 아니면 y, 맞으면 N
n = len(soup.find_all(id='self_icon'))
if n != 0: 
    self_oil = 'y'
else:
    self_oil = 'n'
self_oil

'y'

In [315]:
from tqdm import tqdm
num = 0
for gu_name in tqdm(gu_names):
    # 지역 선택 (강남구로 예시)
    element = driver.find_element(By.CSS_SELECTOR, '#SIGUNGU_NM0')
    element.send_keys(gu_name)
    time.sleep(3)
    
    req = driver.page_source
    soup = BeautifulSoup(req, 'html.parser')
    print(gu_name)
    
    for i in tqdm(range(int(soup.find(id='totCnt').text))):
    # for i in tqdm(range(1)):
        # 첫번째 가게 선택
        oil_store_btn = driver.find_element(By.CSS_SELECTOR, '#body1 > tr:nth-child({}) > td.rlist > a'.format(i+1))
        oil_store_btn.click()
        time.sleep(3)

        req = driver.page_source
        soup = BeautifulSoup(req, 'html.parser')


        name = soup.find_all('div', 'header')[0].text.replace(' ', '')
        name = oil_name(name)
        brand_soup = soup.find_all('img')[6:]
        brand = brand_soup[i]['alt']
        brand = brand_sch(brand)
        address = soup.find('label', id='rd_addr').text
        #휘발유
        gasoline = soup.find('label', id='b027_p').text
        gasoline = Toint(gasoline)
        # 경유
        diesel = soup.find('label', id='d047_p').text
        diesel = Toint(diesel)
        # 셀프주유소: 길이가 0이 아니면 y, 맞으면 N
        n = len(soup.find_all(id='self_icon'))
        if n != 0: 
            self_oil = 1
        else:
            self_oil = 0
        # 세차장: off가 안에 들어있을 경우에는 N
        if 'off' in soup.find(id='cwsh_yn')['src']:
            cwsh = 0
        else:
            cwsh = 1
        # 충전소: off가 안에 들어있을 경우에는 N
        if 'off' in soup.find(id='lpg_yn')['src'] :
            lpg = 0
        else:
            lpg = 1
        # 경정비: off가 안에 들어있을 경우에는 N
        if 'off' in soup.find(id='maint_yn')['src']:
            maint = 0
        else:
            maint = 1
        # 편의점: off가 안에 들어있을 경우에는 N
        if 'off' in soup.find(id='cvs_yn')['src']:
            cvs = 0
        else:
            cvs = 1
        # 24시 영업: off가 안에 들어있을 경우에는 N
        if 'off' in soup.find(id='sel24_yn')['src']:
            sel24 = 0
        else:
            sel24 = 1
        # 구
        gu = gu_sch(address)
             
        # lat, lng
        lat, lng = lat_lng_sch(address)
        a = [num + 1, brand, name, '서울', gu, address, gasoline, diesel, self_oil, cwsh, lpg, maint, cvs, sel24, lat, lng]
        num += 1 
        cursor.execute('insert into GAS_STATION values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)', tuple(a))
        conn.commit()

  0%|          | 0/25 [00:00<?, ?it/s]

강남구

100%|██████████| 32/32 [02:05<00:00,  3.91s/it]
  4%|▍         | 1/25 [02:09<51:52, 129.67s/it]

강동구

100%|██████████| 14/14 [00:52<00:00,  3.74s/it]
  8%|▊         | 2/25 [03:05<33:05, 86.33s/it]

강북구

100%|██████████| 12/12 [00:44<00:00,  3.68s/it]
 12%|█▏        | 3/25 [03:53<25:12, 68.77s/it]

강서구

100%|██████████| 33/33 [02:04<00:00,  3.77s/it]
 16%|█▌        | 4/25 [06:02<32:20, 92.41s/it]

관악구

100%|██████████| 14/14 [00:52<00:00,  3.74s/it]
 20%|██        | 5/25 [06:58<26:25, 79.29s/it]

광진구

100%|██████████| 13/13 [00:48<00:00,  3.74s/it]
 24%|██▍       | 6/25 [07:50<22:12, 70.13s/it]

구로구

100%|██████████| 19/19 [01:10<00:00,  3.73s/it]
 28%|██▊       | 7/25 [09:05<21:28, 71.60s/it]

금천구

100%|██████████| 11/11 [00:40<00:00,  3.70s/it]
 32%|███▏      | 8/25 [09:49<17:50, 62.95s/it]

노원구

100%|██████████| 14/14 [00:51<00:00,  3.69s/it]
 36%|███▌      | 9/25 [10:44<16:09, 60.57s/it]

도봉구

100%|██████████| 16/16 [00:59<00:00,  3.71s/it]
 40%|████      | 10/25 [11:48<15:21, 61.43s/it]

동대문구

100%|██████████| 18/18 [01:06<00:00,  3.72s/it]
 44%|████▍     | 11/25 [12:59<15:01, 64.40s/it]

동작구

100%|██████████| 9/9 [00:33<00:00,  3.71s/it]
 48%|████▊     | 12/25 [13:36<12:08, 56.07s/it]

마포구

100%|██████████| 11/11 [00:40<00:00,  3.70s/it]
 52%|█████▏    | 13/25 [14:20<10:30, 52.52s/it]

서대문구

100%|██████████| 15/15 [00:55<00:00,  3.71s/it]
 56%|█████▌    | 14/25 [15:20<10:00, 54.59s/it]

서초구

100%|██████████| 31/31 [01:56<00:00,  3.76s/it]
 60%|██████    | 15/25 [17:20<12:25, 74.51s/it]

성동구

100%|██████████| 15/15 [00:55<00:00,  3.70s/it]
 64%|██████▍   | 16/25 [18:20<10:29, 69.93s/it]

성북구

100%|██████████| 23/23 [01:25<00:00,  3.72s/it]
 68%|██████▊   | 17/25 [19:49<10:06, 75.76s/it]

송파구

100%|██████████| 28/28 [01:45<00:00,  3.78s/it]
 72%|███████▏  | 18/25 [21:39<10:01, 85.94s/it]

양천구

100%|██████████| 24/24 [01:29<00:00,  3.75s/it]
 76%|███████▌  | 19/25 [23:12<08:49, 88.27s/it]

영등포구

100%|██████████| 27/27 [01:41<00:00,  3.76s/it]
 80%|████████  | 20/25 [24:57<07:46, 93.34s/it]

용산구

100%|██████████| 12/12 [00:44<00:00,  3.69s/it]
 84%|████████▍ | 21/25 [25:45<05:18, 79.71s/it]

은평구

100%|██████████| 15/15 [00:54<00:00,  3.67s/it]
 88%|████████▊ | 22/25 [26:44<03:40, 73.41s/it]

종로구

100%|██████████| 9/9 [00:32<00:00,  3.64s/it]
 92%|█████████▏| 23/25 [27:21<02:04, 62.32s/it]

중구

100%|██████████| 10/10 [00:36<00:00,  3.66s/it]
 96%|█████████▌| 24/25 [28:01<00:55, 55.69s/it]

중랑구

100%|██████████| 13/13 [00:48<00:00,  3.73s/it]
100%|██████████| 25/25 [28:53<00:00, 69.33s/it]

In [287]:
driver.quit()

In [317]:
# 입력된 데이터의 총 개수
cursor.execute('select COUNT(*) from GAS_STATION')
cursor.fetchall()

[(438,)]

In [369]:
# 입력된 데이터 상위 10개
cursor.execute('select * from GAS_STATION limit 10')
cursor.fetchall()

[(1,
  1,
  '(주)보성세곡주유소',
  '서울',
  '강남구',
  '서울 강남구  헌릉로 731 (세곡동)',
  1632,
  1553,
  1,
  1,
  0,
  0,
  0,
  0,
  Decimal('37.4672'),
  Decimal('127.11870810000000')),
 (2,
  2,
  '(주)직영산성셀프주유소',
  '서울',
  '강남구',
  '서울 강남구 헌릉로 730',
  1639,
  1569,
  1,
  1,
  0,
  0,
  0,
  0,
  Decimal('37.4666'),
  Decimal('127.11908030000000')),
 (3,
  3,
  '방죽주유소',
  '서울',
  '강남구',
  '서울 강남구 밤고개로 215 (율현동)',
  1667,
  1599,
  1,
  1,
  0,
  0,
  0,
  0,
  Decimal('37.4750'),
  Decimal('127.10688660000000')),
 (4,
  1,
  '자곡셀프주유소',
  '서울',
  '강남구',
  '서울 강남구 밤고개로 120 (자곡동)',
  1685,
  1599,
  1,
  1,
  0,
  0,
  0,
  0,
  Decimal('37.4834'),
  Decimal('127.10404580000000')),
 (5,
  4,
  '일원주유소',
  '서울',
  '강남구',
  '서울 강남구 양재대로55길 3 (일원동)',
  1687,
  1627,
  1,
  0,
  0,
  0,
  0,
  0,
  Decimal('37.4943'),
  Decimal('127.09419970000000')),
 (6,
  1,
  '(주)중앙에너비스수서지점',
  '서울',
  '강남구',
  '서울 강남구 광평로 202 (수서동)',
  1687,
  1627,
  1,
  1,
  0,
  0,
  0,
  0,
  Decimal('37.4841'),
  Decimal('127.09504010000000')),
 (7,
  2,
  '삼성동주유소',
  '서울',
  '강남구',
  '서울 강남구 테헤란로 619 (삼성동)',
  1689,
  1655,
  1,
  1,
  0,
  0,
  0,
  0,
  Decimal('37.5099'),
  Decimal('127.06511010000000')),
 (8,
  2,
  '(주)직영도곡셀프주유소',
  '서울',
  '강남구',
  '서울 강남구  남부순환로 2718 (도곡2동)',
  1704,
  1624,
  1,
  1,
  0,
  1,
  0,
  0,
  Decimal('37.4855'),
  Decimal('127.04321810000000')),
 (9,
  4,
  '(주)개나리주유소',
  '서울',
  '강남구',
  '서울 강남구 언주로 423 (역삼동)',
  1705,
  1625,
  1,
  1,
  0,
  1,
  0,
  1,
  Decimal('37.5001'),
  Decimal('127.03854190000000')),
 (10,
  2,
  '(주)직영유진주유소',
  '서울',
  '강남구',
  '서울 강남구 논현로 152 (도곡동)',
  1714,
  1639,
  0,
  1,
  0,
  1,
  0,
  0,
  Decimal('37.4874'),
  Decimal('127.03999760000000'))]

문제 5.

시각화 프로젝트를 위하여 다음의 규칙으로 쿼리하여 CSV 파일로 저장합니다. (Python 코드로 작성)
- 전체 데이터를 가져오는데, 주유소 브랜드 아이디 대신 브랜드명이 표시되어야 합니다. (정렬 : 주유소 매장 아이디 순)
- 다음의 형식으로 저장되어야 함 (브랜드 이름, 칼럼 명 주의, id : GAS_STORE.id)

제출 5.
- 시각화 프로젝트 관련 코드 (ipynb), 결과 파일 (csv)

In [318]:
cursor.execute('select * from GAS_STATION')
a = cursor.fetchall()
df = pd.DataFrame(a)

In [319]:
df.columns = ['id', 'brand', 'name', 'city', 'gu', 'address', 'gasoline', 'diesel', 'self', 'car_wash', 'charging_station', 'car_maintenance', 'convenience_store', '24_hours', 'lat', 'lng']
df.head(3)

,id,brand,name,city,gu,address,gasoline,diesel,self,car_wash,charging_station,car_maintenance,convenience_store,24_hours,lat,lng
0,1,1,(주)보성세곡주유소,서울,강남구,서울 강남구 헌릉로 731 (세곡동),1632,1553,1,1,0,0,0,0,37.4672,127.11870810000000
1,2,2,(주)직영산성셀프주유소,서울,강남구,서울 강남구 헌릉로 730,1639,1569,1,1,0,0,0,0,37.4666,127.11908030000000
2,3,3,방죽주유소,서울,강남구,서울 강남구 밤고개로 215 (율현동),1667,1599,1,1,0,0,0,0,37.4750,127.10688660000000

In [321]:
def brand_num(brand):
    return gas_id[brand]

In [325]:
df['brand'] = df['brand'].apply(brand_num)
df.head()

,id,brand,name,city,gu,address,gasoline,diesel,self,car_wash,charging_station,car_maintenance,convenience_store,24_hours,lat,lng
0,1,SK에너지,(주)보성세곡주유소,서울,강남구,서울 강남구 헌릉로 731 (세곡동),1632,1553,1,1,0,0,0,0,37.4672,127.11870810000000
1,2,HD현대오일뱅크,(주)직영산성셀프주유소,서울,강남구,서울 강남구 헌릉로 730,1639,1569,1,1,0,0,0,0,37.4666,127.11908030000000
2,3,GS칼텍스,방죽주유소,서울,강남구,서울 강남구 밤고개로 215 (율현동),1667,1599,1,1,0,0,0,0,37.4750,127.10688660000000
3,4,SK에너지,자곡셀프주유소,서울,강남구,서울 강남구 밤고개로 120 (자곡동),1685,1599,1,1,0,0,0,0,37.4834,127.10404580000000
4,5,S-OIL,일원주유소,서울,강남구,서울 강남구 양재대로55길 3 (일원동),1687,1627,1,0,0,0,0,0,37.4943,127.09419970000000

In [326]:
df = df.sort_values(by='id')

In [327]:
df.head(3)

,id,brand,name,city,gu,address,gasoline,diesel,self,car_wash,charging_station,car_maintenance,convenience_store,24_hours,lat,lng
0,1,SK에너지,(주)보성세곡주유소,서울,강남구,서울 강남구 헌릉로 731 (세곡동),1632,1553,1,1,0,0,0,0,37.4672,127.11870810000000
1,2,HD현대오일뱅크,(주)직영산성셀프주유소,서울,강남구,서울 강남구 헌릉로 730,1639,1569,1,1,0,0,0,0,37.4666,127.11908030000000
2,3,GS칼텍스,방죽주유소,서울,강남구,서울 강남구 밤고개로 215 (율현동),1667,1599,1,1,0,0,0,0,37.4750,127.10688660000000

In [328]:
df.to_csv('C:/Users/kjh25/anaconda/envs/zerobase/ds_study/sql 과제/gas_station.csv')

문제 6.

위도, 경도 정보를 이용하여 미왕빌딩에서 1킬로 이내에 위치한 주유소 정보를 검색하세요.

- 주유소 아이디, 주유소 브랜드명, 주유소 매장명, 주소, 미왕빌딩으로 부터의 거리 (km)

제출 6.
- 쿼리, 결과

In [331]:
lat = gmaps.geocode('강남대로 364')[0]['geometry']['location']['lat']
lng = gmaps.geocode('강남대로 364')[0]['geometry']['location']['lng']
miwang = (lat, lng)
miwang

(37.4955525, 127.0292924)

In [350]:
cursor.execute('SELECT id, brand, name, address, ST_DISTANCE_Sphere(POINT(lng, lat),POINT(127.0292924, 37.4955525)) * 0.001 AS distance from GAS_STATION where ST_DISTANCE_Sphere(POINT(lng, lat),POINT(127.0292924, 37.4955525)) * 0.001 <= 1')
cursor.fetchall()

[(9, 4, '(주)개나리주유소', '서울 강남구 언주로 423 (역삼동)', 0.9599580709982167),
 (13, 1, 'SK서광주유소', '서울 강남구 역삼로 142', 0.5302295839238831),
 (242, 2, '(주)직영서초제일주유소', '서울 서초구 사임당로 116 (서초동)', 0.8070529349095068)]

In [13]:
cursor.execute('select * from GAS_BRAND')
cursor.fetchall()

[(1, 'SK에너지'),
 (2, 'HD현대오일뱅크'),
 (3, 'GS칼텍스'),
 (4, 'S-OIL'),
 (5, '알뜰주유소'),
 (6, '자가상표')]

In [16]:
cursor.execute('''SELECT GS.id, 
       GB.NAME, 
       GS.name, 
       GS.address, 
       ST_DISTANCE_Sphere(POINT(lng, lat), POINT(127.0292924, 37.4955525)) * 0.001 AS distance 
FROM GAS_STATION GS 
LEFT JOIN GAS_BRAND GB ON GS.BRAND = GB.ID  
WHERE ST_DISTANCE_Sphere(POINT(lng, lat), POINT(127.0292924, 37.4955525)) * 0.001 <= 1''')
cursor.fetchall()

[(9, 'S-OIL', '(주)개나리주유소', '서울 강남구 언주로 423 (역삼동)', 0.9599580709982167),
 (13, 'SK에너지', 'SK서광주유소', '서울 강남구 역삼로 142', 0.5302295839238831),
 (242,
  'HD현대오일뱅크',
  '(주)직영서초제일주유소',
  '서울 서초구 사임당로 116 (서초동)',
  0.8070529349095068)]

문제 7.

위도, 경도 정보를 이용하여 미왕빌딩에서 셀프주유가 가능하고 24시간이면서 편의점이 있는 가장 가까운 주유소 10개를 휘 발유 가격이 가장 저렴한 순으로 정렬하여 조회하세요.

- 주유소 아이디, 주유소 브랜드명, 주유소 매장명, 주소, 휘발유 가격, 부가정보 (셀프, 24시간, 편의점 여부), 미왕빌딩으로 부터의 거리 (km)


제출 7.
- 쿼리, 결과

In [362]:
cursor.execute('''
    SELECT a.id, a.brand, a.name, a.address, a.gasoline, a.self, a.24_hours, a.convenience_store, a.distance
    FROM (
        SELECT *, ST_DISTANCE_Sphere(POINT(lng, lat), POINT(127.0292924, 37.4955525)) * 0.001 AS distance 
        FROM GAS_STATION 
        WHERE self=1 AND 24_hours=1 AND convenience_store=1 
        ORDER BY distance 
        LIMIT 10
    ) a
    ORDER BY  a.gasoline
''')
cursor.fetchall()

[(232,
  6,
  '만남의광장주유소',
  '서울 서초구 양재대로12길 73-71',
  1563,
  1,
  1,
  1,
  4.102610088348625),
 (355, 1, '행촌주유소', '서울 영등포구 도신로 130 (신길동)', 1565, 1, 1, 1, 10.951801085420417),
 (219,
  2,
  '(주)가재울뉴타운주유소',
  '서울 서대문구 모래내로 205',
  1612,
  1,
  1,
  1,
  12.787575551687494),
 (302,
  3,
  '지에스칼텍스(주)가든파이브주유소',
  '서울 송파구 탄천동로 740',
  1633,
  1,
  1,
  1,
  5.292842864105397),
 (223,
  1,
  '행촌제2주유소',
  '서울 서대문구 성산로 490 (대신동)',
  1635,
  1,
  1,
  1,
  10.69695327380042),
 (369,
  1,
  'SK에너지(주)기린주유소',
  '서울 영등포구 선유로 270',
  1639,
  1,
  1,
  1,
  12.318300671689821),
 (348,
  2,
  '현대오일뱅크(주)직영양천현대셀프주유소',
  '서울 양천구 안양천로 1179 (목동)',
  1639,
  1,
  1,
  1,
  14.201773373761737),
 (309,
  1,
  '백제고분로주유소',
  '서울 송파구 오금로 143 (방이동)',
  1643,
  1,
  1,
  1,
  7.944650332781823),
 (146,
  3,
  '대득에너지(금천셀프주유소)',
  '서울 금천구  시흥대로 81 (시흥동)',
  1665,
  1,
  1,
  1,
  12.679488648330864),
 (244,
  1,
  '대신석유(주)대우주유소',
  '서울 서초구 양재대로 173 (양재동)',
  1699,
  1,
  1,
  1,
  3.7142143527914)]

In [19]:
cursor.execute('''
SELECT a.id, GB.NAME, a.name, a.address, a.gasoline, a.self, a.24_hours, a.convenience_store, a.distance
    FROM (
        SELECT *, ST_DISTANCE_Sphere(POINT(lng, lat), POINT(127.0292924, 37.4955525)) * 0.001 AS distance 
        FROM GAS_STATION 
        WHERE self=1 AND 24_hours=1 AND convenience_store=1 
        ORDER BY distance 
        LIMIT 10
    ) a left join GAS_BRAND GB ON a.BRAND = GB.ID
    ORDER BY  a.gasoline
''')
cursor.fetchall()

[(232,
  '자가상표',
  '만남의광장주유소',
  '서울 서초구 양재대로12길 73-71',
  1563,
  1,
  1,
  1,
  4.102610088348625),
 (355,
  'SK에너지',
  '행촌주유소',
  '서울 영등포구 도신로 130 (신길동)',
  1565,
  1,
  1,
  1,
  10.951801085420417),
 (219,
  'HD현대오일뱅크',
  '(주)가재울뉴타운주유소',
  '서울 서대문구 모래내로 205',
  1612,
  1,
  1,
  1,
  12.787575551687494),
 (302,
  'GS칼텍스',
  '지에스칼텍스(주)가든파이브주유소',
  '서울 송파구 탄천동로 740',
  1633,
  1,
  1,
  1,
  5.292842864105397),
 (223,
  'SK에너지',
  '행촌제2주유소',
  '서울 서대문구 성산로 490 (대신동)',
  1635,
  1,
  1,
  1,
  10.69695327380042),
 (369,
  'SK에너지',
  'SK에너지(주)기린주유소',
  '서울 영등포구 선유로 270',
  1639,
  1,
  1,
  1,
  12.318300671689821),
 (348,
  'HD현대오일뱅크',
  '현대오일뱅크(주)직영양천현대셀프주유소',
  '서울 양천구 안양천로 1179 (목동)',
  1639,
  1,
  1,
  1,
  14.201773373761737),
 (309,
  'SK에너지',
  '백제고분로주유소',
  '서울 송파구 오금로 143 (방이동)',
  1643,
  1,
  1,
  1,
  7.944650332781823),
 (146,
  'GS칼텍스',
  '대득에너지(금천셀프주유소)',
  '서울 금천구  시흥대로 81 (시흥동)',
  1665,
  1,
  1,
  1,
  12.679488648330864),
 (244,
  'SK에너지',
  '대신석유(주)대우주유소',
  '서울 서초구 양재대로 173 (양재동)',
  1699,
  1,
  1,
  1,
  3.7142143527914)]

문제 8.

구별로 주유소 브랜드 별 휘발유 평균가격을 조회하여 저렴한 순으로 출력하세요.

- 구 이름, 주유소 브랜드 이름, 휘발유 평균 가격

제출 8.
- 쿼리, 결과

In [368]:
cursor.execute('''select gu, brand, avg(gasoline)
               from GAS_STATION
               group by gu, brand
               order by avg(gasoline)''')
cursor.fetchall()

[('양천구', 4, Decimal('1554.0000')),
 ('양천구', 6, Decimal('1557.0000')),
 ('강서구', 6, Decimal('1559.5000')),
 ('서초구', 6, Decimal('1563.0000')),
 ('영등포구', 6, Decimal('1565.0000')),
 ('구로구', 1, Decimal('1580.5000')),
 ('성북구', 6, Decimal('1585.0000')),
 ('중랑구', 2, Decimal('1587.0000')),
 ('성동구', 6, Decimal('1588.0000')),
 ('중랑구', 3, Decimal('1593.6667')),
 ('강북구', 2, Decimal('1595.6667')),
 ('은평구', 2, Decimal('1596.5000')),
 ('도봉구', 3, Decimal('1601.6667')),
 ('양천구', 3, Decimal('1603.2000')),
 ('강북구', 4, Decimal('1605.0000')),
 ('광진구', 2, Decimal('1605.1667')),
 ('강북구', 1, Decimal('1605.2500')),
 ('도봉구', 2, Decimal('1606.6667')),
 ('중랑구', 4, Decimal('1607.2000')),
 ('도봉구', 4, Decimal('1607.8000')),
 ('성북구', 1, Decimal('1608.0000')),
 ('동대문구', 3, Decimal('1609.6667')),
 ('성북구', 2, Decimal('1611.2857')),
 ('도봉구', 1, Decimal('1615.0000')),
 ('강북구', 3, Decimal('1616.3333')),
 ('동대문구', 1, Decimal('1616.4000')),
 ('성동구', 4, Decimal('1618.5000')),
 ('영등포구', 4, Decimal('1621.3333')),
 ('은평구', 1, Decimal('1621.6667')),
 ('광진구', 3, Decimal('1622.0000')),
 ('강서구', 2, Decimal('1622.4000')),
 ('양천구', 1, Decimal('1623.0000')),
 ('은평구', 3, Decimal('1624.6000')),
 ('금천구', 4, Decimal('1625.0000')),
 ('서대문구', 2, Decimal('1626.2500')),
 ('금천구', 6, Decimal('1628.0000')),
 ('노원구', 2, Decimal('1628.3333')),
 ('동대문구', 2, Decimal('1630.0000')),
 ('노원구', 1, Decimal('1632.0000')),
 ('성북구', 3, Decimal('1633.6667')),
 ('양천구', 2, Decimal('1633.6667')),
 ('동대문구', 4, Decimal('1634.2500')),
 ('서대문구', 4, Decimal('1634.3333')),
 ('서대문구', 3, Decimal('1636.0000')),
 ('노원구', 4, Decimal('1637.0000')),
 ('성북구', 4, Decimal('1637.6667')),
 ('관악구', 6, Decimal('1639.0000')),
 ('서대문구', 1, Decimal('1643.3333')),
 ('구로구', 2, Decimal('1648.8750')),
 ('금천구', 1, Decimal('1650.3333')),
 ('송파구', 4, Decimal('1650.4000')),
 ('중랑구', 1, Decimal('1651.2500')),
 ('관악구', 1, Decimal('1653.5000')),
 ('관악구', 2, Decimal('1654.0000')),
 ('은평구', 4, Decimal('1654.5000')),
 ('동작구', 3, Decimal('1657.0000')),
 ('영등포구', 2, Decimal('1657.1429')),
 ('광진구', 4, Decimal('1658.6667')),
 ('금천구', 2, Decimal('1658.6667')),
 ('마포구', 2, Decimal('1664.3333')),
 ('금천구', 3, Decimal('1665.0000')),
 ('송파구', 3, Decimal('1668.5000')),
 ('노원구', 3, Decimal('1669.6000')),
 ('송파구', 2, Decimal('1670.6667')),
 ('중구', 4, Decimal('1674.5000')),
 ('중구', 6, Decimal('1678.0000')),
 ('동작구', 4, Decimal('1679.0000')),
 ('강서구', 3, Decimal('1684.4286')),
 ('동작구', 2, Decimal('1686.0000')),
 ('강서구', 1, Decimal('1686.3636')),
 ('송파구', 1, Decimal('1686.4444')),
 ('서초구', 2, Decimal('1688.8000')),
 ('강서구', 4, Decimal('1690.8333')),
 ('마포구', 4, Decimal('1695.6667')),
 ('광진구', 1, Decimal('1698.0000')),
 ('종로구', 2, Decimal('1706.5000')),
 ('구로구', 4, Decimal('1707.7500')),
 ('서초구', 3, Decimal('1708.6667')),
 ('마포구', 1, Decimal('1715.4000')),
 ('관악구', 4, Decimal('1721.0000')),
 ('은평구', 6, Decimal('1728.0000')),
 ('강동구', 2, Decimal('1734.0000')),
 ('영등포구', 1, Decimal('1736.0000')),
 ('강동구', 3, Decimal('1745.0000')),
 ('성동구', 2, Decimal('1752.6667')),
 ('관악구', 3, Decimal('1757.3333')),
 ('강동구', 1, Decimal('1760.5000')),
 ('영등포구', 3, Decimal('1761.1250')),
 ('서초구', 1, Decimal('1765.0000')),
 ('서초구', 4, Decimal('1772.1667')),
 ('종로구', 4, Decimal('1779.0000')),
 ('동작구', 1, Decimal('1785.0000')),
 ('구로구', 3, Decimal('1797.6667')),
 ('성동구', 1, Decimal('1823.6667')),
 ('중구', 2, Decimal('1828.0000')),
 ('강남구', 4, Decimal('1836.2500')),
 ('강남구', 1, Decimal('1841.6364')),
 ('강동구', 4, Decimal('1899.0000')),
 ('강남구', 2, Decimal('1944.3750')),
 ('성동구', 3, Decimal('1949.0000')),
 ('강남구', 3, Decimal('2006.7778')),
 ('용산구', 2, Decimal('2011.7500')),
 ('중구', 1, Decimal('2065.0000')),
 ('종로구', 1, Decimal('2101.3333')),
 ('용산구', 1, Decimal('2177.1667')),
 ('종로구', 3, Decimal('2315.0000')),
 ('용산구', 3, Decimal('2346.5000')),
 ('중구', 3, Decimal('2409.0000'))]

In [20]:
cursor.execute('''select GS.gu, GB.name, GS.gasoline
from (select gu, brand, avg(gasoline) AS gasoline
               from GAS_STATION 
               group by gu, brand
               order by avg(gasoline)) GS left join GAS_BRAND GB ON GS.BRAND = GB.ID''')
cursor.fetchall()

[('양천구', 'S-OIL', Decimal('1554.0000')),
 ('양천구', '자가상표', Decimal('1557.0000')),
 ('강서구', '자가상표', Decimal('1559.5000')),
 ('서초구', '자가상표', Decimal('1563.0000')),
 ('영등포구', '자가상표', Decimal('1565.0000')),
 ('구로구', 'SK에너지', Decimal('1580.5000')),
 ('성북구', '자가상표', Decimal('1585.0000')),
 ('중랑구', 'HD현대오일뱅크', Decimal('1587.0000')),
 ('성동구', '자가상표', Decimal('1588.0000')),
 ('중랑구', 'GS칼텍스', Decimal('1593.6667')),
 ('강북구', 'HD현대오일뱅크', Decimal('1595.6667')),
 ('은평구', 'HD현대오일뱅크', Decimal('1596.5000')),
 ('도봉구', 'GS칼텍스', Decimal('1601.6667')),
 ('양천구', 'GS칼텍스', Decimal('1603.2000')),
 ('강북구', 'S-OIL', Decimal('1605.0000')),
 ('광진구', 'HD현대오일뱅크', Decimal('1605.1667')),
 ('강북구', 'SK에너지', Decimal('1605.2500')),
 ('도봉구', 'HD현대오일뱅크', Decimal('1606.6667')),
 ('중랑구', 'S-OIL', Decimal('1607.2000')),
 ('도봉구', 'S-OIL', Decimal('1607.8000')),
 ('성북구', 'SK에너지', Decimal('1608.0000')),
 ('동대문구', 'GS칼텍스', Decimal('1609.6667')),
 ('성북구', 'HD현대오일뱅크', Decimal('1611.2857')),
 ('도봉구', 'SK에너지', Decimal('1615.0000')),
 ('강북구', 'GS칼텍스', Decimal('1616.3333')),
 ('동대문구', 'SK에너지', Decimal('1616.4000')),
 ('성동구', 'S-OIL', Decimal('1618.5000')),
 ('영등포구', 'S-OIL', Decimal('1621.3333')),
 ('은평구', 'SK에너지', Decimal('1621.6667')),
 ('광진구', 'GS칼텍스', Decimal('1622.0000')),
 ('강서구', 'HD현대오일뱅크', Decimal('1622.4000')),
 ('양천구', 'SK에너지', Decimal('1623.0000')),
 ('은평구', 'GS칼텍스', Decimal('1624.6000')),
 ('금천구', 'S-OIL', Decimal('1625.0000')),
 ('서대문구', 'HD현대오일뱅크', Decimal('1626.2500')),
 ('금천구', '자가상표', Decimal('1628.0000')),
 ('노원구', 'HD현대오일뱅크', Decimal('1628.3333')),
 ('동대문구', 'HD현대오일뱅크', Decimal('1630.0000')),
 ('노원구', 'SK에너지', Decimal('1632.0000')),
 ('성북구', 'GS칼텍스', Decimal('1633.6667')),
 ('양천구', 'HD현대오일뱅크', Decimal('1633.6667')),
 ('동대문구', 'S-OIL', Decimal('1634.2500')),
 ('서대문구', 'S-OIL', Decimal('1634.3333')),
 ('서대문구', 'GS칼텍스', Decimal('1636.0000')),
 ('노원구', 'S-OIL', Decimal('1637.0000')),
 ('성북구', 'S-OIL', Decimal('1637.6667')),
 ('관악구', '자가상표', Decimal('1639.0000')),
 ('서대문구', 'SK에너지', Decimal('1643.3333')),
 ('구로구', 'HD현대오일뱅크', Decimal('1648.8750')),
 ('금천구', 'SK에너지', Decimal('1650.3333')),
 ('송파구', 'S-OIL', Decimal('1650.4000')),
 ('중랑구', 'SK에너지', Decimal('1651.2500')),
 ('관악구', 'SK에너지', Decimal('1653.5000')),
 ('관악구', 'HD현대오일뱅크', Decimal('1654.0000')),
 ('은평구', 'S-OIL', Decimal('1654.5000')),
 ('동작구', 'GS칼텍스', Decimal('1657.0000')),
 ('영등포구', 'HD현대오일뱅크', Decimal('1657.1429')),
 ('광진구', 'S-OIL', Decimal('1658.6667')),
 ('금천구', 'HD현대오일뱅크', Decimal('1658.6667')),
 ('마포구', 'HD현대오일뱅크', Decimal('1664.3333')),
 ('금천구', 'GS칼텍스', Decimal('1665.0000')),
 ('송파구', 'GS칼텍스', Decimal('1668.5000')),
 ('노원구', 'GS칼텍스', Decimal('1669.6000')),
 ('송파구', 'HD현대오일뱅크', Decimal('1670.6667')),
 ('중구', 'S-OIL', Decimal('1674.5000')),
 ('중구', '자가상표', Decimal('1678.0000')),
 ('동작구', 'S-OIL', Decimal('1679.0000')),
 ('강서구', 'GS칼텍스', Decimal('1684.4286')),
 ('동작구', 'HD현대오일뱅크', Decimal('1686.0000')),
 ('강서구', 'SK에너지', Decimal('1686.3636')),
 ('송파구', 'SK에너지', Decimal('1686.4444')),
 ('서초구', 'HD현대오일뱅크', Decimal('1688.8000')),
 ('강서구', 'S-OIL', Decimal('1690.8333')),
 ('마포구', 'S-OIL', Decimal('1695.6667')),
 ('광진구', 'SK에너지', Decimal('1698.0000')),
 ('종로구', 'HD현대오일뱅크', Decimal('1706.5000')),
 ('구로구', 'S-OIL', Decimal('1707.7500')),
 ('서초구', 'GS칼텍스', Decimal('1708.6667')),
 ('마포구', 'SK에너지', Decimal('1715.4000')),
 ('관악구', 'S-OIL', Decimal('1721.0000')),
 ('은평구', '자가상표', Decimal('1728.0000')),
 ('강동구', 'HD현대오일뱅크', Decimal('1734.0000')),
 ('영등포구', 'SK에너지', Decimal('1736.0000')),
 ('강동구', 'GS칼텍스', Decimal('1745.0000')),
 ('성동구', 'HD현대오일뱅크', Decimal('1752.6667')),
 ('관악구', 'GS칼텍스', Decimal('1757.3333')),
 ('강동구', 'SK에너지', Decimal('1760.5000')),
 ('영등포구', 'GS칼텍스', Decimal('1761.1250')),
 ('서초구', 'SK에너지', Decimal('1765.0000')),
 ('서초구', 'S-OIL', Decimal('1772.1667')),
 ('종로구', 'S-OIL', Decimal('1779.0000')),
 ('동작구', 'SK에너지', Decimal('1785.0000')),
 ('구로구', 'GS칼텍스', Decimal('1797.6667')),
 ('성동구', 'SK에너지', Decimal('1823.6667')),
 ('중구', 'HD현대오일뱅크', Decimal('1828.0000')),
 ('강남구', 'S-OIL', Decimal('1836.2500')),
 ('강남구', 'SK에너지', Decimal('1841.6364')),
 ('강동구', 'S-OIL', Decimal('1899.0000')),
 ('강남구', 'HD현대오일뱅크', Decimal('1944.3750')),
 ('성동구', 'GS칼텍스', Decimal('1949.0000')),
 ('강남구', 'GS칼텍스', Decimal('2006.7778')),
 ('용산구', 'HD현대오일뱅크', Decimal('2011.7500')),
 ('중구', 'SK에너지', Decimal('2065.0000')),
 ('종로구', 'SK에너지', Decimal('2101.3333')),
 ('용산구', 'SK에너지', Decimal('2177.1667')),
 ('종로구', 'GS칼텍스', Decimal('2315.0000')),
 ('용산구', 'GS칼텍스', Decimal('2346.5000')),
 ('중구', 'GS칼텍스', Decimal('2409.0000'))]

---